//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnswerQuestionTUI.ConQuestionServiceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Map MapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Player[] PlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet QuestionSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Map Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Player[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet QuestionSet {
            get {
                return this.QuestionSetField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionSetField, value) != true)) {
                    this.QuestionSetField = value;
                    this.RaisePropertyChanged("QuestionSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Map", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Map : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionSet", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class QuestionSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Question[] QuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Question[] Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Answer[] AnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Answer[] Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoundAction", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class RoundAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.PlayerAnswer[] PlayerAnswersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.PlayerAnswer[] PlayerAnswers {
            get {
                return this.PlayerAnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerAnswersField, value) != true)) {
                    this.PlayerAnswersField = value;
                    this.RaisePropertyChanged("PlayerAnswers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerAnswer", Namespace="http://schemas.datacontract.org/2004/07/ConquestionGame.Domain")]
    [System.SerializableAttribute()]
    public partial class PlayerAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Answer answerGivenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AnswerQuestionTUI.ConQuestionServiceTest.Player playerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double timeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Answer answerGiven {
            get {
                return this.answerGivenField;
            }
            set {
                if ((object.ReferenceEquals(this.answerGivenField, value) != true)) {
                    this.answerGivenField = value;
                    this.RaisePropertyChanged("answerGiven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnswerQuestionTUI.ConQuestionServiceTest.Player player {
            get {
                return this.playerField;
            }
            set {
                if ((object.ReferenceEquals(this.playerField, value) != true)) {
                    this.playerField = value;
                    this.RaisePropertyChanged("player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((this.timeStampField.Equals(value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConQuestionServiceTest.IConquestionService")]
    public interface IConquestionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreatePlayer", ReplyAction="http://tempuri.org/IConquestionService/CreatePlayerResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.Player CreatePlayer(AnswerQuestionTUI.ConQuestionServiceTest.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreatePlayer", ReplyAction="http://tempuri.org/IConquestionService/CreatePlayerResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Player> CreatePlayerAsync(AnswerQuestionTUI.ConQuestionServiceTest.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame", ReplyAction="http://tempuri.org/IConquestionService/CreateGameResponse")]
        void CreateGame(AnswerQuestionTUI.ConQuestionServiceTest.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CreateGame", ReplyAction="http://tempuri.org/IConquestionService/CreateGameResponse")]
        System.Threading.Tasks.Task CreateGameAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddPlayer", ReplyAction="http://tempuri.org/IConquestionService/AddPlayerResponse")]
        void AddPlayer(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AddPlayer", ReplyAction="http://tempuri.org/IConquestionService/AddPlayerResponse")]
        System.Threading.Tasks.Task AddPlayerAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ActiveGames", ReplyAction="http://tempuri.org/IConquestionService/ActiveGamesResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.Game[] ActiveGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ActiveGames", ReplyAction="http://tempuri.org/IConquestionService/ActiveGamesResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Game[]> ActiveGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ChoseGame", ReplyAction="http://tempuri.org/IConquestionService/ChoseGameResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.Game ChoseGame(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ChoseGame", ReplyAction="http://tempuri.org/IConquestionService/ChoseGameResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Game> ChoseGameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllQuestionSets", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllQuestionSetsResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet[] RetrieveAllQuestionSets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllQuestionSets", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllQuestionSetsResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet[]> RetrieveAllQuestionSetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllMaps", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllMapsResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.Map[] RetrieveAllMaps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/RetrieveAllMaps", ReplyAction="http://tempuri.org/IConquestionService/RetrieveAllMapsResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Map[]> RetrieveAllMapsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AskQuestion", ReplyAction="http://tempuri.org/IConquestionService/AskQuestionResponse")]
        AnswerQuestionTUI.ConQuestionServiceTest.Question AskQuestion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/AskQuestion", ReplyAction="http://tempuri.org/IConquestionService/AskQuestionResponse")]
        System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Question> AskQuestionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ValidateAnswer", ReplyAction="http://tempuri.org/IConquestionService/ValidateAnswerResponse")]
        bool ValidateAnswer(int userAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/ValidateAnswer", ReplyAction="http://tempuri.org/IConquestionService/ValidateAnswerResponse")]
        System.Threading.Tasks.Task<bool> ValidateAnswerAsync(int userAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckPlayerAnswers", ReplyAction="http://tempuri.org/IConquestionService/CheckPlayerAnswersResponse")]
        bool CheckPlayerAnswers(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.RoundAction roundAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConquestionService/CheckPlayerAnswers", ReplyAction="http://tempuri.org/IConquestionService/CheckPlayerAnswersResponse")]
        System.Threading.Tasks.Task<bool> CheckPlayerAnswersAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.RoundAction roundAction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConquestionServiceChannel : AnswerQuestionTUI.ConQuestionServiceTest.IConquestionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConquestionServiceClient : System.ServiceModel.ClientBase<AnswerQuestionTUI.ConQuestionServiceTest.IConquestionService>, AnswerQuestionTUI.ConQuestionServiceTest.IConquestionService {
        
        public ConquestionServiceClient() {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConquestionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConquestionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.Player CreatePlayer(AnswerQuestionTUI.ConQuestionServiceTest.Player player) {
            return base.Channel.CreatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Player> CreatePlayerAsync(AnswerQuestionTUI.ConQuestionServiceTest.Player player) {
            return base.Channel.CreatePlayerAsync(player);
        }
        
        public void CreateGame(AnswerQuestionTUI.ConQuestionServiceTest.Game game) {
            base.Channel.CreateGame(game);
        }
        
        public System.Threading.Tasks.Task CreateGameAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game) {
            return base.Channel.CreateGameAsync(game);
        }
        
        public void AddPlayer(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.Player player) {
            base.Channel.AddPlayer(game, player);
        }
        
        public System.Threading.Tasks.Task AddPlayerAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.Player player) {
            return base.Channel.AddPlayerAsync(game, player);
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.Game[] ActiveGames() {
            return base.Channel.ActiveGames();
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Game[]> ActiveGamesAsync() {
            return base.Channel.ActiveGamesAsync();
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.Game ChoseGame(string name) {
            return base.Channel.ChoseGame(name);
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Game> ChoseGameAsync(string name) {
            return base.Channel.ChoseGameAsync(name);
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet[] RetrieveAllQuestionSets() {
            return base.Channel.RetrieveAllQuestionSets();
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.QuestionSet[]> RetrieveAllQuestionSetsAsync() {
            return base.Channel.RetrieveAllQuestionSetsAsync();
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.Map[] RetrieveAllMaps() {
            return base.Channel.RetrieveAllMaps();
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Map[]> RetrieveAllMapsAsync() {
            return base.Channel.RetrieveAllMapsAsync();
        }
        
        public AnswerQuestionTUI.ConQuestionServiceTest.Question AskQuestion() {
            return base.Channel.AskQuestion();
        }
        
        public System.Threading.Tasks.Task<AnswerQuestionTUI.ConQuestionServiceTest.Question> AskQuestionAsync() {
            return base.Channel.AskQuestionAsync();
        }
        
        public bool ValidateAnswer(int userAnswer) {
            return base.Channel.ValidateAnswer(userAnswer);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateAnswerAsync(int userAnswer) {
            return base.Channel.ValidateAnswerAsync(userAnswer);
        }
        
        public bool CheckPlayerAnswers(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.RoundAction roundAction) {
            return base.Channel.CheckPlayerAnswers(game, roundAction);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPlayerAnswersAsync(AnswerQuestionTUI.ConQuestionServiceTest.Game game, AnswerQuestionTUI.ConQuestionServiceTest.RoundAction roundAction) {
            return base.Channel.CheckPlayerAnswersAsync(game, roundAction);
        }
    }
}
